/*
     _____ __    _____
    |     |  |  |_   _|  C++ Object Libraries for IBM i
    |  |  |  |__ _| |_   File:   OBJECT/define.h
    |_____|_____|_____|  Author: Sergey Chebotarev

*/

#ifndef OLI_OBJECT_DEFINE_H
#define OLI_OBJECT_DEFINE_H


#pragma comment(user, "General characteristics of IBM i system objects")


#define FS_NAMESPACE_BEGIN namespace fs {
#define FS_NAMESPACE_END }


#endif // OLI_OBJECT_DEFINE_H

