/*
     _____ _____ __
    |   __|_   _|  |     Standard library implementation for IBM i
    |__   | | | |  |__   File:   STL/define.h
    |_____| |_| |_____|  Author: Sergey Chebotarev

*/

#ifndef OLI_STL_DEFINE_H
#define OLI_STL_DEFINE_H


#pragma comment(user, "Standard library implementation for IBM i")


#define STL_NAMESPACE_BEGIN namespace stl {
#define STL_NAMESPACE_END }


#endif // OLI_STL_DEFINE_H

