/*
     _____ _____ __
    |   __|_   _|  |     Standard library implementation for IBM i
    |__   | | | |  |__   File:   STL/utility.h
    |_____| |_| |_____|  Author: Sergey Chebotarev

*/

#ifndef OLI_STL_UTILITY_H_
#define OLI_STL_UTILITY_H_

#include "STL/typetraits.h"

STL_NAMESPACE_BEGIN ////////////////////////////////////////////////////////////
STL_NAMESPACE_END //////////////////////////////////////////////////////////////

#endif // OLI_STL_UTILITY_H_

