/*
     _____ __    _____
    |     |  |  |_   _|  C++ Object Libraries for IBM i
    |  |  |  |__ _| |_   File:   CORE/olidef.h
    |_____|_____|_____|  Author: Sergey Chebotarev

*/

#ifndef OLI_CORE_OLIDEF_H
#define OLI_CORE_OLIDEF_H


#pragma comment(copyright, "This program uses the C++ object libraries for IBM i (OLI).")
#pragma comment(user, "Sergey Chebotarev (d7d1cd@gmail.com).")


#define IBM_NAMESPACE_BEGIN namespace ibm { inline namespace v1 {
#define IBM_NAMESPACE_END }}


#define STL_NAMESPACE_BEGIN namespace stl {
#define STL_NAMESPACE_END }


#endif // OLI_CORE_OLIDEF_H

