/*
     _____ __    _____
    |     |  |  |_   _|  C++ Object Library for IBM i
    |  |  |  |__ _| |_   File:   CORE/olidef.h
    |_____|_____|_____|  Author: S.N. Chebotarev

*/

#ifndef OLI_CORE_OLIDEF_H_
#define OLI_CORE_OLIDEF_H_


#pragma comment(copyright, "This program uses the C++ object library for IBM i (OLI).")
#pragma comment(user, "S. N. Chebotarev (d7d1cd@gmail.com).")


#define OLI_NAMESPACE_BEGIN namespace oli { inline namespace v1 {
#define OLI_NAMESPACE_END }}


#define STL_NAMESPACE_BEGIN namespace stl {
#define STL_NAMESPACE_END }


#define __IBMCPP_TR1__ 1                                                        // Включение возможностей C++ technical report 1


#endif // OLI_CORE_OLIDEF_H_

